# Generated by Django 3.2.16 on 2022-12-07 17:11

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221206_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='short_title',
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
    ]
