# Generated by Django 3.2.16 on 2022-12-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20221207_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='imagetitle',
            field=models.CharField(max_length=70, null=True, unique=True, verbose_name='Название изображения'),
        ),
        migrations.AlterField(
            model_name='place',
            name='place_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(max_length=150, unique=True, verbose_name='Название места'),
        ),
    ]
